/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as TenantsRouteImport } from './routes/tenants'
import { Route as SmartLockRouteImport } from './routes/smart-lock'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ParkingRouteImport } from './routes/parking'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as CctvRouteImport } from './routes/cctv'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as BookingLeadsRouteImport } from './routes/booking-leads'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AccessHistoryRouteImport } from './routes/access-history'
import { Route as IndexRouteImport } from './routes/index'

const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsRoute = TenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartLockRoute = SmartLockRouteImport.update({
  id: '/smart-lock',
  path: '/smart-lock',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkingRoute = ParkingRouteImport.update({
  id: '/parking',
  path: '/parking',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const CctvRoute = CctvRouteImport.update({
  id: '/cctv',
  path: '/cctv',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessHistoryRoute = AccessHistoryRouteImport.update({
  id: '/access-history',
  path: '/access-history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-history': typeof AccessHistoryRoute
  '/booking': typeof BookingRoute
  '/bookings': typeof BookingsRoute
  '/cctv': typeof CctvRoute
  '/complaints': typeof ComplaintsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/parking': typeof ParkingRoute
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/rooms': typeof RoomsRoute
  '/settings': typeof SettingsRoute
  '/smart-lock': typeof SmartLockRoute
  '/tenants': typeof TenantsRoute
  '/vehicles': typeof VehiclesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-history': typeof AccessHistoryRoute
  '/booking': typeof BookingRoute
  '/bookings': typeof BookingsRoute
  '/cctv': typeof CctvRoute
  '/complaints': typeof ComplaintsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/parking': typeof ParkingRoute
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/rooms': typeof RoomsRoute
  '/settings': typeof SettingsRoute
  '/smart-lock': typeof SmartLockRoute
  '/tenants': typeof TenantsRoute
  '/vehicles': typeof VehiclesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-history': typeof AccessHistoryRoute
  '/booking': typeof BookingRoute
  '/bookings': typeof BookingsRoute
  '/cctv': typeof CctvRoute
  '/complaints': typeof ComplaintsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/parking': typeof ParkingRoute
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/rooms': typeof RoomsRoute
  '/settings': typeof SettingsRoute
  '/smart-lock': typeof SmartLockRoute
  '/tenants': typeof TenantsRoute
  '/vehicles': typeof VehiclesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-history'
    | '/booking'
    | '/bookings'
    | '/cctv'
    | '/complaints'
    | '/login'
    | '/notifications'
    | '/parking'
    | '/payments'
    | '/reports'
    | '/rooms'
    | '/settings'
    | '/smart-lock'
    | '/tenants'
    | '/vehicles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-history'
    | '/booking'
    | '/bookings'
    | '/cctv'
    | '/complaints'
    | '/login'
    | '/notifications'
    | '/parking'
    | '/payments'
    | '/reports'
    | '/rooms'
    | '/settings'
    | '/smart-lock'
    | '/tenants'
    | '/vehicles'
  id:
    | '__root__'
    | '/'
    | '/access-history'
    | '/booking'
    | '/bookings'
    | '/cctv'
    | '/complaints'
    | '/login'
    | '/notifications'
    | '/parking'
    | '/payments'
    | '/reports'
    | '/rooms'
    | '/settings'
    | '/smart-lock'
    | '/tenants'
    | '/vehicles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessHistoryRoute: typeof AccessHistoryRoute
  BookingRoute: typeof BookingRoute
  BookingsRoute: typeof BookingsRoute
  CctvRoute: typeof CctvRoute
  ComplaintsRoute: typeof ComplaintsRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ParkingRoute: typeof ParkingRoute
  PaymentsRoute: typeof PaymentsRoute
  ReportsRoute: typeof ReportsRoute
  RoomsRoute: typeof RoomsRoute
  SettingsRoute: typeof SettingsRoute
  SmartLockRoute: typeof SmartLockRoute
  TenantsRoute: typeof TenantsRoute
  VehiclesRoute: typeof VehiclesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants': {
      id: '/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof TenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-lock': {
      id: '/smart-lock'
      path: '/smart-lock'
      fullPath: '/smart-lock'
      preLoaderRoute: typeof SmartLockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parking': {
      id: '/parking'
      path: '/parking'
      fullPath: '/parking'
      preLoaderRoute: typeof ParkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cctv': {
      id: '/cctv'
      path: '/cctv'
      fullPath: '/cctv'
      preLoaderRoute: typeof CctvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-history': {
      id: '/access-history'
      path: '/access-history'
      fullPath: '/access-history'
      preLoaderRoute: typeof AccessHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessHistoryRoute: AccessHistoryRoute,
  BookingRoute: BookingRoute,
  BookingsRoute: BookingsRoute,
  CctvRoute: CctvRoute,
  ComplaintsRoute: ComplaintsRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ParkingRoute: ParkingRoute,
  PaymentsRoute: PaymentsRoute,
  ReportsRoute: ReportsRoute,
  RoomsRoute: RoomsRoute,
  SettingsRoute: SettingsRoute,
  SmartLockRoute: SmartLockRoute,
  TenantsRoute: TenantsRoute,
  VehiclesRoute: VehiclesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
