/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as TenantsRouteImport } from './routes/tenants'
import { Route as SyaratKetentuanRouteImport } from './routes/syarat-ketentuan'
import { Route as SmartLockRouteImport } from './routes/smart-lock'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ParkingRouteImport } from './routes/parking'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HunianGalleryRouteImport } from './routes/hunian-gallery'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as CctvRouteImport } from './routes/cctv'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as BookingLeadsRouteImport } from './routes/booking-leads'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AccessHistoryRouteImport } from './routes/access-history'
import { Route as RoomsRouteRouteImport } from './routes/rooms/route'
import { Route as PenyewaanRouteRouteImport } from './routes/penyewaan/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsIndexRouteImport } from './routes/rooms/index'
import { Route as PenyewaanIndexRouteImport } from './routes/penyewaan/index'
import { Route as RoomsRumahKostRouteImport } from './routes/rooms/rumah-kost'
import { Route as RoomsGaleriRouteImport } from './routes/rooms/galeri'
import { Route as RoomsFasilitasRouteImport } from './routes/rooms/fasilitas'
import { Route as RoomsApartKostRouteImport } from './routes/rooms/apart-kost'
import { Route as RoomsRoomNumberRouteImport } from './routes/rooms/$roomNumber'
import { Route as PenyewaanTambahRouteImport } from './routes/penyewaan/tambah'
import { Route as PenyewaanLeaseIdRouteImport } from './routes/penyewaan/$leaseId'

const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsRoute = TenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const SyaratKetentuanRoute = SyaratKetentuanRouteImport.update({
  id: '/syarat-ketentuan',
  path: '/syarat-ketentuan',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartLockRoute = SmartLockRouteImport.update({
  id: '/smart-lock',
  path: '/smart-lock',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkingRoute = ParkingRouteImport.update({
  id: '/parking',
  path: '/parking',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HunianGalleryRoute = HunianGalleryRouteImport.update({
  id: '/hunian-gallery',
  path: '/hunian-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const CctvRoute = CctvRouteImport.update({
  id: '/cctv',
  path: '/cctv',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingLeadsRoute = BookingLeadsRouteImport.update({
  id: '/booking-leads',
  path: '/booking-leads',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessHistoryRoute = AccessHistoryRouteImport.update({
  id: '/access-history',
  path: '/access-history',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRouteRoute = RoomsRouteRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const PenyewaanRouteRoute = PenyewaanRouteRouteImport.update({
  id: '/penyewaan',
  path: '/penyewaan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoomsRouteRoute,
} as any)
const PenyewaanIndexRoute = PenyewaanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PenyewaanRouteRoute,
} as any)
const RoomsRumahKostRoute = RoomsRumahKostRouteImport.update({
  id: '/rumah-kost',
  path: '/rumah-kost',
  getParentRoute: () => RoomsRouteRoute,
} as any)
const RoomsGaleriRoute = RoomsGaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => RoomsRouteRoute,
} as any)
const RoomsFasilitasRoute = RoomsFasilitasRouteImport.update({
  id: '/fasilitas',
  path: '/fasilitas',
  getParentRoute: () => RoomsRouteRoute,
} as any)
const RoomsApartKostRoute = RoomsApartKostRouteImport.update({
  id: '/apart-kost',
  path: '/apart-kost',
  getParentRoute: () => RoomsRouteRoute,
} as any)
const RoomsRoomNumberRoute = RoomsRoomNumberRouteImport.update({
  id: '/$roomNumber',
  path: '/$roomNumber',
  getParentRoute: () => RoomsRouteRoute,
} as any)
const PenyewaanTambahRoute = PenyewaanTambahRouteImport.update({
  id: '/tambah',
  path: '/tambah',
  getParentRoute: () => PenyewaanRouteRoute,
} as any)
const PenyewaanLeaseIdRoute = PenyewaanLeaseIdRouteImport.update({
  id: '/$leaseId',
  path: '/$leaseId',
  getParentRoute: () => PenyewaanRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/penyewaan': typeof PenyewaanRouteRouteWithChildren
  '/rooms': typeof RoomsRouteRouteWithChildren
  '/access-history': typeof AccessHistoryRoute
  '/booking': typeof BookingRoute
  '/booking-leads': typeof BookingLeadsRoute
  '/bookings': typeof BookingsRoute
  '/cctv': typeof CctvRoute
  '/complaints': typeof ComplaintsRoute
  '/hunian-gallery': typeof HunianGalleryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/parking': typeof ParkingRoute
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/smart-lock': typeof SmartLockRoute
  '/syarat-ketentuan': typeof SyaratKetentuanRoute
  '/tenants': typeof TenantsRoute
  '/vehicles': typeof VehiclesRoute
  '/penyewaan/$leaseId': typeof PenyewaanLeaseIdRoute
  '/penyewaan/tambah': typeof PenyewaanTambahRoute
  '/rooms/$roomNumber': typeof RoomsRoomNumberRoute
  '/rooms/apart-kost': typeof RoomsApartKostRoute
  '/rooms/fasilitas': typeof RoomsFasilitasRoute
  '/rooms/galeri': typeof RoomsGaleriRoute
  '/rooms/rumah-kost': typeof RoomsRumahKostRoute
  '/penyewaan/': typeof PenyewaanIndexRoute
  '/rooms/': typeof RoomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-history': typeof AccessHistoryRoute
  '/booking': typeof BookingRoute
  '/booking-leads': typeof BookingLeadsRoute
  '/bookings': typeof BookingsRoute
  '/cctv': typeof CctvRoute
  '/complaints': typeof ComplaintsRoute
  '/hunian-gallery': typeof HunianGalleryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/parking': typeof ParkingRoute
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/smart-lock': typeof SmartLockRoute
  '/syarat-ketentuan': typeof SyaratKetentuanRoute
  '/tenants': typeof TenantsRoute
  '/vehicles': typeof VehiclesRoute
  '/penyewaan/$leaseId': typeof PenyewaanLeaseIdRoute
  '/penyewaan/tambah': typeof PenyewaanTambahRoute
  '/rooms/$roomNumber': typeof RoomsRoomNumberRoute
  '/rooms/apart-kost': typeof RoomsApartKostRoute
  '/rooms/fasilitas': typeof RoomsFasilitasRoute
  '/rooms/galeri': typeof RoomsGaleriRoute
  '/rooms/rumah-kost': typeof RoomsRumahKostRoute
  '/penyewaan': typeof PenyewaanIndexRoute
  '/rooms': typeof RoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/penyewaan': typeof PenyewaanRouteRouteWithChildren
  '/rooms': typeof RoomsRouteRouteWithChildren
  '/access-history': typeof AccessHistoryRoute
  '/booking': typeof BookingRoute
  '/booking-leads': typeof BookingLeadsRoute
  '/bookings': typeof BookingsRoute
  '/cctv': typeof CctvRoute
  '/complaints': typeof ComplaintsRoute
  '/hunian-gallery': typeof HunianGalleryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/parking': typeof ParkingRoute
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/smart-lock': typeof SmartLockRoute
  '/syarat-ketentuan': typeof SyaratKetentuanRoute
  '/tenants': typeof TenantsRoute
  '/vehicles': typeof VehiclesRoute
  '/penyewaan/$leaseId': typeof PenyewaanLeaseIdRoute
  '/penyewaan/tambah': typeof PenyewaanTambahRoute
  '/rooms/$roomNumber': typeof RoomsRoomNumberRoute
  '/rooms/apart-kost': typeof RoomsApartKostRoute
  '/rooms/fasilitas': typeof RoomsFasilitasRoute
  '/rooms/galeri': typeof RoomsGaleriRoute
  '/rooms/rumah-kost': typeof RoomsRumahKostRoute
  '/penyewaan/': typeof PenyewaanIndexRoute
  '/rooms/': typeof RoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/penyewaan'
    | '/rooms'
    | '/access-history'
    | '/booking'
    | '/booking-leads'
    | '/bookings'
    | '/cctv'
    | '/complaints'
    | '/hunian-gallery'
    | '/login'
    | '/notifications'
    | '/parking'
    | '/payments'
    | '/reports'
    | '/settings'
    | '/smart-lock'
    | '/syarat-ketentuan'
    | '/tenants'
    | '/vehicles'
    | '/penyewaan/$leaseId'
    | '/penyewaan/tambah'
    | '/rooms/$roomNumber'
    | '/rooms/apart-kost'
    | '/rooms/fasilitas'
    | '/rooms/galeri'
    | '/rooms/rumah-kost'
    | '/penyewaan/'
    | '/rooms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-history'
    | '/booking'
    | '/booking-leads'
    | '/bookings'
    | '/cctv'
    | '/complaints'
    | '/hunian-gallery'
    | '/login'
    | '/notifications'
    | '/parking'
    | '/payments'
    | '/reports'
    | '/settings'
    | '/smart-lock'
    | '/syarat-ketentuan'
    | '/tenants'
    | '/vehicles'
    | '/penyewaan/$leaseId'
    | '/penyewaan/tambah'
    | '/rooms/$roomNumber'
    | '/rooms/apart-kost'
    | '/rooms/fasilitas'
    | '/rooms/galeri'
    | '/rooms/rumah-kost'
    | '/penyewaan'
    | '/rooms'
  id:
    | '__root__'
    | '/'
    | '/penyewaan'
    | '/rooms'
    | '/access-history'
    | '/booking'
    | '/booking-leads'
    | '/bookings'
    | '/cctv'
    | '/complaints'
    | '/hunian-gallery'
    | '/login'
    | '/notifications'
    | '/parking'
    | '/payments'
    | '/reports'
    | '/settings'
    | '/smart-lock'
    | '/syarat-ketentuan'
    | '/tenants'
    | '/vehicles'
    | '/penyewaan/$leaseId'
    | '/penyewaan/tambah'
    | '/rooms/$roomNumber'
    | '/rooms/apart-kost'
    | '/rooms/fasilitas'
    | '/rooms/galeri'
    | '/rooms/rumah-kost'
    | '/penyewaan/'
    | '/rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PenyewaanRouteRoute: typeof PenyewaanRouteRouteWithChildren
  RoomsRouteRoute: typeof RoomsRouteRouteWithChildren
  AccessHistoryRoute: typeof AccessHistoryRoute
  BookingRoute: typeof BookingRoute
  BookingLeadsRoute: typeof BookingLeadsRoute
  BookingsRoute: typeof BookingsRoute
  CctvRoute: typeof CctvRoute
  ComplaintsRoute: typeof ComplaintsRoute
  HunianGalleryRoute: typeof HunianGalleryRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ParkingRoute: typeof ParkingRoute
  PaymentsRoute: typeof PaymentsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SmartLockRoute: typeof SmartLockRoute
  SyaratKetentuanRoute: typeof SyaratKetentuanRoute
  TenantsRoute: typeof TenantsRoute
  VehiclesRoute: typeof VehiclesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants': {
      id: '/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof TenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syarat-ketentuan': {
      id: '/syarat-ketentuan'
      path: '/syarat-ketentuan'
      fullPath: '/syarat-ketentuan'
      preLoaderRoute: typeof SyaratKetentuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-lock': {
      id: '/smart-lock'
      path: '/smart-lock'
      fullPath: '/smart-lock'
      preLoaderRoute: typeof SmartLockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parking': {
      id: '/parking'
      path: '/parking'
      fullPath: '/parking'
      preLoaderRoute: typeof ParkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hunian-gallery': {
      id: '/hunian-gallery'
      path: '/hunian-gallery'
      fullPath: '/hunian-gallery'
      preLoaderRoute: typeof HunianGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cctv': {
      id: '/cctv'
      path: '/cctv'
      fullPath: '/cctv'
      preLoaderRoute: typeof CctvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-leads': {
      id: '/booking-leads'
      path: '/booking-leads'
      fullPath: '/booking-leads'
      preLoaderRoute: typeof BookingLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-history': {
      id: '/access-history'
      path: '/access-history'
      fullPath: '/access-history'
      preLoaderRoute: typeof AccessHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penyewaan': {
      id: '/penyewaan'
      path: '/penyewaan'
      fullPath: '/penyewaan'
      preLoaderRoute: typeof PenyewaanRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof RoomsRouteRoute
    }
    '/penyewaan/': {
      id: '/penyewaan/'
      path: '/'
      fullPath: '/penyewaan/'
      preLoaderRoute: typeof PenyewaanIndexRouteImport
      parentRoute: typeof PenyewaanRouteRoute
    }
    '/rooms/rumah-kost': {
      id: '/rooms/rumah-kost'
      path: '/rumah-kost'
      fullPath: '/rooms/rumah-kost'
      preLoaderRoute: typeof RoomsRumahKostRouteImport
      parentRoute: typeof RoomsRouteRoute
    }
    '/rooms/galeri': {
      id: '/rooms/galeri'
      path: '/galeri'
      fullPath: '/rooms/galeri'
      preLoaderRoute: typeof RoomsGaleriRouteImport
      parentRoute: typeof RoomsRouteRoute
    }
    '/rooms/fasilitas': {
      id: '/rooms/fasilitas'
      path: '/fasilitas'
      fullPath: '/rooms/fasilitas'
      preLoaderRoute: typeof RoomsFasilitasRouteImport
      parentRoute: typeof RoomsRouteRoute
    }
    '/rooms/apart-kost': {
      id: '/rooms/apart-kost'
      path: '/apart-kost'
      fullPath: '/rooms/apart-kost'
      preLoaderRoute: typeof RoomsApartKostRouteImport
      parentRoute: typeof RoomsRouteRoute
    }
    '/rooms/$roomNumber': {
      id: '/rooms/$roomNumber'
      path: '/$roomNumber'
      fullPath: '/rooms/$roomNumber'
      preLoaderRoute: typeof RoomsRoomNumberRouteImport
      parentRoute: typeof RoomsRouteRoute
    }
    '/penyewaan/tambah': {
      id: '/penyewaan/tambah'
      path: '/tambah'
      fullPath: '/penyewaan/tambah'
      preLoaderRoute: typeof PenyewaanTambahRouteImport
      parentRoute: typeof PenyewaanRouteRoute
    }
    '/penyewaan/$leaseId': {
      id: '/penyewaan/$leaseId'
      path: '/$leaseId'
      fullPath: '/penyewaan/$leaseId'
      preLoaderRoute: typeof PenyewaanLeaseIdRouteImport
      parentRoute: typeof PenyewaanRouteRoute
    }
  }
}

interface PenyewaanRouteRouteChildren {
  PenyewaanLeaseIdRoute: typeof PenyewaanLeaseIdRoute
  PenyewaanTambahRoute: typeof PenyewaanTambahRoute
  PenyewaanIndexRoute: typeof PenyewaanIndexRoute
}

const PenyewaanRouteRouteChildren: PenyewaanRouteRouteChildren = {
  PenyewaanLeaseIdRoute: PenyewaanLeaseIdRoute,
  PenyewaanTambahRoute: PenyewaanTambahRoute,
  PenyewaanIndexRoute: PenyewaanIndexRoute,
}

const PenyewaanRouteRouteWithChildren = PenyewaanRouteRoute._addFileChildren(
  PenyewaanRouteRouteChildren,
)

interface RoomsRouteRouteChildren {
  RoomsRoomNumberRoute: typeof RoomsRoomNumberRoute
  RoomsApartKostRoute: typeof RoomsApartKostRoute
  RoomsFasilitasRoute: typeof RoomsFasilitasRoute
  RoomsGaleriRoute: typeof RoomsGaleriRoute
  RoomsRumahKostRoute: typeof RoomsRumahKostRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
}

const RoomsRouteRouteChildren: RoomsRouteRouteChildren = {
  RoomsRoomNumberRoute: RoomsRoomNumberRoute,
  RoomsApartKostRoute: RoomsApartKostRoute,
  RoomsFasilitasRoute: RoomsFasilitasRoute,
  RoomsGaleriRoute: RoomsGaleriRoute,
  RoomsRumahKostRoute: RoomsRumahKostRoute,
  RoomsIndexRoute: RoomsIndexRoute,
}

const RoomsRouteRouteWithChildren = RoomsRouteRoute._addFileChildren(
  RoomsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PenyewaanRouteRoute: PenyewaanRouteRouteWithChildren,
  RoomsRouteRoute: RoomsRouteRouteWithChildren,
  AccessHistoryRoute: AccessHistoryRoute,
  BookingRoute: BookingRoute,
  BookingLeadsRoute: BookingLeadsRoute,
  BookingsRoute: BookingsRoute,
  CctvRoute: CctvRoute,
  ComplaintsRoute: ComplaintsRoute,
  HunianGalleryRoute: HunianGalleryRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ParkingRoute: ParkingRoute,
  PaymentsRoute: PaymentsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SmartLockRoute: SmartLockRoute,
  SyaratKetentuanRoute: SyaratKetentuanRoute,
  TenantsRoute: TenantsRoute,
  VehiclesRoute: VehiclesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
