/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KamarRouteImport } from './routes/kamar'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as KamarSlugRouteImport } from './routes/kamar.$slug'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppInfoRouteImport } from './routes/_app/info'
import { Route as AppComplaintsRouteImport } from './routes/_app/complaints'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AppBillingRouteImport } from './routes/_app/billing'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KamarRoute = KamarRouteImport.update({
  id: '/kamar',
  path: '/kamar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const KamarSlugRoute = KamarSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KamarRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppInfoRoute = AppInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => AppRoute,
} as any)
const AppComplaintsRoute = AppComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/kamar': typeof KamarRouteWithChildren
  '/login': typeof LoginRoute
  '/billing': typeof AppBillingRoute
  '/chat': typeof AppChatRoute
  '/complaints': typeof AppComplaintsRoute
  '/info': typeof AppInfoRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/kamar/$slug': typeof KamarSlugRoute
}
export interface FileRoutesByTo {
  '/kamar': typeof KamarRouteWithChildren
  '/login': typeof LoginRoute
  '/billing': typeof AppBillingRoute
  '/chat': typeof AppChatRoute
  '/complaints': typeof AppComplaintsRoute
  '/info': typeof AppInfoRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/kamar/$slug': typeof KamarSlugRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/kamar': typeof KamarRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/complaints': typeof AppComplaintsRoute
  '/_app/info': typeof AppInfoRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/kamar/$slug': typeof KamarSlugRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kamar'
    | '/login'
    | '/billing'
    | '/chat'
    | '/complaints'
    | '/info'
    | '/notifications'
    | '/profile'
    | '/kamar/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/kamar'
    | '/login'
    | '/billing'
    | '/chat'
    | '/complaints'
    | '/info'
    | '/notifications'
    | '/profile'
    | '/kamar/$slug'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/kamar'
    | '/login'
    | '/_app/billing'
    | '/_app/chat'
    | '/_app/complaints'
    | '/_app/info'
    | '/_app/notifications'
    | '/_app/profile'
    | '/kamar/$slug'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  KamarRoute: typeof KamarRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kamar': {
      id: '/kamar'
      path: '/kamar'
      fullPath: '/kamar'
      preLoaderRoute: typeof KamarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/kamar/$slug': {
      id: '/kamar/$slug'
      path: '/$slug'
      fullPath: '/kamar/$slug'
      preLoaderRoute: typeof KamarSlugRouteImport
      parentRoute: typeof KamarRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/info': {
      id: '/_app/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof AppInfoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/complaints': {
      id: '/_app/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof AppComplaintsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppChatRoute: typeof AppChatRoute
  AppComplaintsRoute: typeof AppComplaintsRoute
  AppInfoRoute: typeof AppInfoRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppChatRoute: AppChatRoute,
  AppComplaintsRoute: AppComplaintsRoute,
  AppInfoRoute: AppInfoRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface KamarRouteChildren {
  KamarSlugRoute: typeof KamarSlugRoute
}

const KamarRouteChildren: KamarRouteChildren = {
  KamarSlugRoute: KamarSlugRoute,
}

const KamarRouteWithChildren = KamarRoute._addFileChildren(KamarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  KamarRoute: KamarRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
